### ISSUE TITLE
Additional props in the link component

### ISSUE THREAD

**Issue by jowo-io** [ianmcgregor/react-micro-router#10]
Hi there, thanks for the great micro-library. I use it on all my single page apps!
I've just come across an issue where I need to pass additional props into the `anchor` tag that's returned from the `Link` component. Specifically needing to set a custom `tabIndex`.

Perhaps we could update the `Link` component like so:
```
export function Link({
    children,
    className,
    exact = false,
    to,
    href,
    replace = false,
    activeClassName = "active",
    match = null,
    ...rest // ADDITION
}) {
    const path = to || href;

    function onClick(event) {
        event.preventDefault();
        redirect(path, replace);
    }

    if (
        isMatch(path, exact ? exact : path === "/") ||
        (match && isMatch(match, exact))
    ) {
        className = `${className} ${activeClassName}`.trim();
    }

    return (
        <a className={className} href={path} onClick={onClick} {...rest}> // ADDITION
            {children}
        </a>
    );
}
```

**Comment by jowo-io** [comment]
or alternatively just add `tabIndex` explicitly, as i guess that will be less likely to create breaking changes!

**Comment by ianmcgregor** [comment]
Hi @jowo-io that makes a lot of sense! Would you like to submit a PR for that and I'll merge/update it on npm?

**Comment by jowo-io** [comment]
yeah definitely can do so, I'll  try and do it this week.
thanks for the quick response

**Comment by jowo-io** [comment]
I opened a PR [here](https://github.com/ianmcgregor/react-micro-router/pull/12)
